version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: cloud_time_tracker_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud_time_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cloud_time_tracker_network

  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: cloud_time_tracker_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cloudtimestracker.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin/servers/cloud_time_tracker_servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cloud_time_tracker_network

networks:
  cloud_time_tracker_network:
    driver: bridge

volumes:
  postgres_data:
