quarkus.datasource.db-kind=${DB_KIND:sqlite}
quarkus.datasource.jdbc.url=jdbc:sqlite:dev.db
quarkus.datasource.jdbc.max-size=16

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
quarkus.hibernate-orm.database.generation=none



%dev.postgres.quarkus.datasource.db-kind=postgresql
%dev.postgres.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cloud_time_tracker}
%dev.postgres.quarkus.datasource.username=${DB_USER:postgres}
%dev.postgres.quarkus.datasource.password=${DB_PASSWORD:postgres}
%dev.postgres.quarkus.datasource.jdbc.max-size=16
%dev.postgres.quarkus.flyway.migrate-at-start=true
%dev.postgres.quarkus.flyway.locations=db/migration
%dev.postgres.quarkus.hibernate-orm.database.generation=none

%prod.postgres.quarkus.datasource.db-kind=postgresql
%prod.postgres.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cloud_time_tracker}
%prod.postgres.quarkus.datasource.username=${DB_USER:postgres}
%prod.postgres.quarkus.datasource.password=${DB_PASSWORD:postgres}
%prod.postgres.quarkus.datasource.jdbc.max-size=16
%prod.postgres.quarkus.flyway.migrate-at-start=true
%prod.postgres.quarkus.flyway.locations=db/migration
%prod.postgres.quarkus.hibernate-orm.database.generation=none

%it.quarkus.datasource.db-kind=sqlite
%it.quarkus.datasource.jdbc.url=jdbc:sqlite::memory:
%it.quarkus.datasource.jdbc.max-size=16
%it.quarkus.flyway.migrate-at-start=true
%it.quarkus.flyway.locations=db/test_data
%it.quarkus.hibernate-orm.database.generation=none
%it.quarkus.log.category."org.flywaydb".level=DEBUG
